### ISSUE TITLE
Issue with installing the node packages on a windows machine

### ISSUE THREAD

**Issue by apoorv74** [erikaris/rplaywright#1]
While running `rplaywright_npm_install`, I got this error - 

> Error in `process_initialize(self, private, command, args, stdin, stdout, ...`:
> ! Native call to `processx_exec` failed
> Caused by error in `chain_call(c_processx_exec, command, c(command, args), pty, pty_options, ...`:
> ! Command 'npm' not found @win/processx.c:982 (processx_exec)
> Type .Last.error to see the more details.

I had npm installed, the npm path was added to the environment variables as well. I was able to run `system2("npm")` . The [issue](https://github.com/r-lib/processx/issues/273) seems to be with how processx runs batch files in Windows.

I was able to run the below command without any issues. 

```
processx::run(
    command = "cmd.exe",
    args = c("/c","npm","ci"),
    wd = system.file("node", package = "rplaywright")
)
```

**Comment by erikaris** [comment]
Hi Apoorv, thank you for your input. Yes, you are right. Apparently, processx causes some issues on Windows. I fix this problem by using [system2](https://rdocumentation.org/packages/base/versions/3.6.2/topics/system2) instead of processx. I have tried it on a Windows machine, and it works. 
Please try it again and let me know if it works this time. 
You might need to uninstall the previously installed rplaywright and re-install it. 
Thanks.

**Comment by apoorv74** [comment]
Works as expected. Closing the issue.
